coverage:
  precision: 2
  round: down
  range: 90...100

  status:
    project:
      default:
        threshold: 6%
        target: 90%

ignore:
  - "contracts/marketplace/src/testing/.*"
  - "contracts/reserve-auction/src/tests/.*"
  - "packages/sg-marketplace-common/src/tests/.*"
