name: E2E Integration Tests

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  test:
    name: E2E tests
    runs-on: ubuntu-latest
    env:
      GAS_OUT_DIR: gas_reports
      ENABLE_MAX_COLLECTION: true
      GAS_LIMIT: 75000000
      MAINNET_GAS_LIMIT: 0
    steps:
      - name: Checkout sources
        uses: actions/checkout@v3

      - name: Install latest nightly toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: nightly
          targets: wasm32-unknown-unknown

      - name: Rust Dependencies Cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
            artifacts/
          key: ${{ runner.os }}-cargo-with-artifacts-${{ hashFiles('**/Cargo.lock') }}

      - name: Get mainnet GAS_LIMIT
        run: echo "MAINNET_GAS_LIMIT=$(curl -s https://rpc.stargaze-apis.com/consensus_params | jq -r '.result.consensus_params.block.max_gas')" >> $GITHUB_ENV

      - name: Mainnet block GAS_LIMIT changed
        if: ${{ env.MAINNET_GAS_LIMIT != env.GAS_LIMIT }}
        uses: actions/github-script@v6
        with:
          script: core.setFailed(`Integration tests must update GAS_LIMIT from ${process.env.GAS_LIMIT} to ${process.env.MAINNET_GAS_LIMIT}`)

      - uses: extractions/setup-just@v1

      - name: Run e2e test
        run: just e2e-test-full
